# Generated by Django 3.0.5 on 2021-12-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('playerType', models.CharField(max_length=50)),
                ('jerseyNumber', models.IntegerField()),
            ],
        ),
    ]
